### ISSUE TITLE
[Bug]: Input type "number" not supported with Zod (client-side validation failure)

### ISSUE THREAD

**Issue by 92dev** [airjp73/rvf#414]
### Which packages are impacted?

- [X] `@rvf/react`
- [ ] `@rvf/react-router`
- [X] `@rvf/zod`
- [ ] `@rvf/yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

    "@rvf/react": "^7.0.1",
    "@rvf/zod": "^7.0.1",
    "zod": "^3.24.1",

### Please provide a link to a minimal reproduction of the issue.

https://google.com/?q=in%20issue

### Steps to Reproduce the Bug or Issue

Create a numeric field and use input type `number`:

```
import { z } from 'zod';
import { withZod } from "@rvf/zod";
import { useForm, useField, useFieldArray } from "@rvf/react";

const schema = z.object({
	num: z.number().min(0).step(0.5)
})

export default function testPage() {
	const zForm = useForm({
		validator: withZod(schema),
		defaultValues: { num: 0 }
	});
	const numField = useField(zForm.scope('num'));

	return (
		<>
			<form {...zForm.getFormProps()}>
				<input {...numField.getInputProps()} type="number" placeholder="test" />
				{numField.error() && (
					<p className="text-sm text-destructive mt-1 font-bold">
						{numField.error()}
					</p>
				)}
			</form>
		</>
	);
}
```

### Expected behavior

Pass numeric type to Zod for proper validation

### Platform

all

### Additional context

Probably same issue as https://github.com/react-hook-form/resolvers/issues/73
need to use`valueAsNumber` when validating a `z.number` typed field

**Comment by 92dev** [comment]
As a workaround, you can `corerce` the schema to do the conversion itself via:
```
const schema = z.object({
	num: z.coerce.number().min(0).step(0.5)
})
```

I just feel like if `number` is supported, it should just be supported out-of-the-box, so I don't need to do
`schema.extend({ field: z.corece"copy-pasta-definition" })` on each such field

**Comment by airjp73** [comment]
Hi! By default, validation is done against the [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) pulled directly out of the native form element. `FormData` only supports strings or arrays of strings, so that's what gets passed into the validator ([docs](https://www.rvf-js.io/input-types#validating)).

If you want a more react-hook-form like experience, you can pass `submitSource: "state"` to the `useForm` hook ([state mode docs](https://www.rvf-js.io/state-mode)). Then the data passed to the validator should be an actual number. For that to work properly, though, you also need to pass the `type` prop through `getInputProps` itself like this `getInputProps({ type: "number" })` ([docs](https://www.rvf-js.io/reference/field-api#get-input-props)).

If this still doesn't work, please feel free to re-open the issue with a reproduction. 😄

**Comment by 92dev** [comment]
Thanks for the detailed comment and hard work
I honestly still believe that if `number` is allowed in schema - it should be handled that way when validating, but as you mentioned - if only strings are supported and you don't want to introduce meta-hell with understanding schema type convertible options, then it is acceptable.

Regardless, for now i just moved to `submitSource: "state"` as suggested since we are using a very complex case which dynamic form layouts based on selection of fields and for the love of me i cannot manage Controlled components with it without getting into weird bugs like using SHADCN select having to spread the ID/VALUE between the "Value" and "Trigger"

**Comment by airjp73** [comment]
Yeah, I've always been really wary of solutions that rely on schema introspection.

Another option if you wanted to avoid state mode (though honestly I use state mode almost exclusively in non-remix projects), would be to use [zod-form-data](https://www.npmjs.com/package/zod-form-data).
